### ISSUE TITLE
Error when build For spark

### ISSUE THREAD

**Issue by kingvuplus** [Taapat/vuplus-openpli-oe-core#11]
Log data follows:
| DEBUG: Executing python function sysroot_cleansstate
| DEBUG: Python function sysroot_cleansstate finished
| DEBUG: SITE files ['endian-little', 'bit-32', 'sh-common', 'common-linux', 'common-glibc', 'sh4-linux', 'common']
| DEBUG: Executing shell function autotools_preconfigure
| DEBUG: Shell function autotools_preconfigure finished
| DEBUG: Executing python function autotools_copy_aclocals
| DEBUG: SITE files ['endian-little', 'bit-32', 'sh-common', 'common-linux', 'common-glibc', 'sh4-linux', 'common']
| DEBUG: Python function autotools_copy_aclocals finished
| DEBUG: Executing shell function do_configure
| automake (GNU automake) 1.15
| Copyright (C) 2014 Free Software Foundation, Inc.
| License GPLv2+: GNU GPL version 2 or later http://gnu.org/licenses/gpl-2.0.html
| This is free software: you are free to change and redistribute it.
| There is NO WARRANTY, to the extent permitted by law.
| 
| Written by Tom Tromey tromey@redhat.com
|        and Alexandre Duret-Lutz adl@gnu.org.
| AUTOV is 1
| NOTE: Executing ACLOCAL="aclocal --system-acdir=/home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/work/sh4-oe-linux/readymedia/1.1.0+gitAUTOINC+bb9d584a86-r0/git/aclocal-copy/" autoreconf --verbose --install --force --exclude=autopoint
| autoreconf: Entering directory `.'
| autoreconf: running: aclocal --system-acdir=/home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/work/sh4-oe-linux/readymedia/1.1.0+gitAUTOINC+bb9d584a86-r0/git/aclocal-copy/ --force -I m4
| autoreconf: configure.ac: tracing
| autoreconf: configure.ac: not using Libtool
| autoreconf: running: /home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/i686-linux/usr/bin/autoconf --force
| autoreconf: running: /home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/i686-linux/usr/bin/autoheader --force
| autoreconf: running: automake --add-missing --copy --force-missing
| configure.ac:25: installing './compile'
| configure.ac:20: installing './config.guess'
| configure.ac:20: installing './config.sub'
| configure.ac:21: installing './install-sh'
| configure.ac:21: installing './missing'
| Makefile.am: installing './depcomp'
| autoreconf: running: gnu-configize
| autoreconf: Leaving directory`.'
| NOTE: Running ./configure  --build=i686-linux           --host=sh4-oe-linux         --target=sh4-oe-linux           --prefix=/usr           --exec_prefix=/usr          --bindir=/usr/bin           --sbindir=/usr/sbin         --libexecdir=/usr/libexec           --datadir=/usr/share        --sysconfdir=/etc           --sharedstatedir=/com           --localstatedir=/var        --libdir=/usr/lib           --includedir=/usr/include           --oldincludedir=/usr/include        --infodir=/usr/share/info           --mandir=/usr/share/man         --disable-silent-rules      --disable-dependency-tracking           --with-libtool-sysroot=/home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark  --enable-nls
| configure: WARNING: unrecognized options: --with-libtool-sysroot
| configure: loading site script /home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/oe-meta-openembedded/meta-oe/site/endian-little
| configure: loading site script /home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/oe-openembedded-core/meta/site/endian-little
| configure: loading site script /home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/oe-openembedded-core/meta/site/sh-common
| configure: loading site script /home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/oe-openembedded-core/meta/site/common-linux
| configure: loading site script /home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/oe-openembedded-core/meta/site/common-glibc
| configure: loading site script /home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/oe-openembedded-core/meta/site/common
| configure: loading site script /home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/work/sh4-oe-linux/readymedia/1.1.0+gitAUTOINC+bb9d584a86-r0/git/aclocal-copy/glibc_config
| configure: loading site script /home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/work/sh4-oe-linux/readymedia/1.1.0+gitAUTOINC+bb9d584a86-r0/git/aclocal-copy/ncurses_config
| checking build system type... i686-pc-linux-gnu
| checking host system type... sh4-oe-linux-gnu
| checking target system type... sh4-oe-linux-gnu
| checking for a BSD-compatible install... /usr/bin/install -c
| checking whether build environment is sane... yes
| checking for sh4-oe-linux-strip... sh4-oe-linux-strip
| checking for a thread-safe mkdir -p... /bin/mkdir -p
| checking for gawk... gawk
| checking whether make sets $(MAKE)... yes
| checking whether make supports nested variables... yes
| checking whether make supports nested variables... (cached) yes
| checking for style of include used by make... GNU
| checking for sh4-oe-linux-gcc... sh4-oe-linux-gcc  -ml -m4 --sysroot=/home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark
| checking whether the C compiler works... yes
| checking for C compiler default output file name... a.out
| checking for suffix of executables...
| checking whether we are cross compiling... yes
| checking for suffix of object files... o
| checking whether we are using the GNU C compiler... yes
| checking whether sh4-oe-linux-gcc  -ml -m4 --sysroot=/home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark accepts -g... yes
| checking for sh4-oe-linux-gcc  -ml -m4 --sysroot=/home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark option to accept ISO C89... none needed
| checking whether sh4-oe-linux-gcc  -ml -m4 --sysroot=/home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark understands -c and -o together... yes
| checking dependency style of sh4-oe-linux-gcc  -ml -m4 --sysroot=/home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark... none
| checking how to run the C preprocessor... sh4-oe-linux-gcc -E --sysroot=/home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark  -ml -m4
| checking for grep that handles long lines and -e... /bin/grep
| checking for egrep... /bin/grep -E
| checking for ANSI C header files... (cached) yes
| checking for sys/types.h... (cached) yes
| checking for sys/stat.h... (cached) yes
| checking for stdlib.h... (cached) yes
| checking for string.h... (cached) yes
| checking for memory.h... (cached) yes
| checking for strings.h... (cached) yes
| checking for inttypes.h... (cached) yes
| checking for stdint.h... (cached) yes
| checking for unistd.h... (cached) yes
| checking minix/config.h usability... no
| checking minix/config.h presence... no
| checking for minix/config.h... no
| checking whether it is safe to define **EXTENSIONS**... yes
| checking for ld used by sh4-oe-linux-gcc  -ml -m4 --sysroot=/home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark... sh4-oe-linux-ld --sysroot=/home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark
| checking if the linker (sh4-oe-linux-ld --sysroot=/home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark ) is GNU ld... yes
| checking for shared library run path origin... done
| checking for iconv... yes
| checking for working iconv... guessing yes
| checking for iconv declaration...
|          extern size_t iconv (iconv_t cd, char \* *inbuf, size_t *inbytesleft, char \* *outbuf, size_t *outbytesleft);
| checking for a sed that does not truncate output... (cached) sed
| checking whether NLS is requested... yes
| checking for msgfmt... /home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/i686-linux/usr/bin/msgfmt
| checking for gmsgfmt... /home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/i686-linux/usr/bin/msgfmt
| checking for xgettext... /home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/i686-linux/usr/bin/xgettext
| checking for msgmerge... /home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/i686-linux/usr/bin/msgmerge
| checking for CFPreferencesCopyAppValue... no
| checking for CFLocaleCopyCurrent... no
| checking for GNU gettext in libc... yes
| checking whether to use NLS... yes
| checking where the gettext function comes from... libc
| checking for gawk... (cached) gawk
| checking for sh4-oe-linux-gcc... (cached) sh4-oe-linux-gcc  -ml -m4 --sysroot=/home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark
| checking whether we are using the GNU C compiler... (cached) yes
| checking whether sh4-oe-linux-gcc  -ml -m4 --sysroot=/home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark accepts -g... (cached) yes
| checking for sh4-oe-linux-gcc  -ml -m4 --sysroot=/home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark option to accept ISO C89... (cached) none needed
| checking whether sh4-oe-linux-gcc  -ml -m4 --sysroot=/home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark understands -c and -o together... (cached) yes
| checking dependency style of sh4-oe-linux-gcc  -ml -m4 --sysroot=/home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark... (cached) none
| checking whether ln -s works... yes
| checking whether make sets $(MAKE)... (cached) yes
| checking for inline... inline
| checking for mode_t... yes
| checking for off_t... yes
| checking for pid_t... yes
| checking for size_t... yes
| checking for uint8_t... yes
| checking for int32_t... yes
| checking for uint32_t... yes
| checking for uint64_t... yes
| checking for ssize_t... yes
| checking for dirent.h that defines DIR... yes
| checking for library containing opendir... none required
| checking for struct dirent.d_type... yes
| checking for struct stat.st_blocks... yes
| checking for stdbool.h that conforms to C99... (cached) yes
| checking for _Bool... yes
| checking whether byte ordering is bigendian... (cached) no
| checking vfork.h usability... no
| checking vfork.h presence... no
| checking for vfork.h... no
| checking for fork... (cached) yes
| checking for vfork... (cached) yes
| checking for working fork... cross
| configure: WARNING: result yes guessed because of cross compilation
| checking for working vfork... (cached) yes
| checking whether lstat correctly handles trailing slash... (cached) yes
| checking for gethostname... (cached) yes
| checking for getifaddrs... (cached) yes
| checking for gettimeofday... (cached) yes
| checking for inet_ntoa... (cached) yes
| checking for memmove... (cached) yes
| checking for memset... (cached) yes
| checking for mkdir... (cached) yes
| checking for realpath... (cached) yes
| checking for select... (cached) yes
| checking for sendfile... yes
| checking for setlocale... (cached) yes
| checking for socket... (cached) yes
| checking for strcasecmp... (cached) yes
| checking for strchr... (cached) yes
| checking for strdup... (cached) yes
| checking for strerror... (cached) yes
| checking for strncasecmp... (cached) yes
| checking for strpbrk... (cached) yes
| checking for strrchr... (cached) yes
| checking for strstr... (cached) yes
| checking for strtol... (cached) yes
| checking for strtoul... (cached) yes
| checking for struct ip_mreqn... yes
| checking syscall.h usability... yes
| checking syscall.h presence... yes
| checking for syscall.h... yes
| checking sys/syscall.h usability... yes
| checking sys/syscall.h presence... yes
| checking for sys/syscall.h... yes
| checking mach/mach_time.h usability... no
| checking mach/mach_time.h presence... no
| checking for mach/mach_time.h... no
| checking for __NR_clock_gettime syscall... yes
| checking for linux/netlink.h... yes
| checking libavutil/avutil.h usability... yes
| checking libavutil/avutil.h presence... yes
| checking for libavutil/avutil.h... yes
| checking ffmpeg/libavutil/avutil.h usability... no
| checking ffmpeg/libavutil/avutil.h presence... no
| checking for ffmpeg/libavutil/avutil.h... no
| checking libav/libavutil/avutil.h usability... no
| checking libav/libavutil/avutil.h presence... no
| checking for libav/libavutil/avutil.h... no
| checking avutil.h usability... no
| checking avutil.h presence... no
| checking for avutil.h... no
| checking ffmpeg/avutil.h usability... no
| checking ffmpeg/avutil.h presence... no
| checking for ffmpeg/avutil.h... no
| checking libav/avutil.h usability... no
| checking libav/avutil.h presence... no
| checking for libav/avutil.h... no
| checking libavcodec/avcodec.h usability... yes
| checking libavcodec/avcodec.h presence... yes
| checking for libavcodec/avcodec.h... yes
| checking ffmpeg/libavcodec/avcodec.h usability... no
| checking ffmpeg/libavcodec/avcodec.h presence... no
| checking for ffmpeg/libavcodec/avcodec.h... no
| checking libav/libavcodec/avcodec.h usability... no
| checking libav/libavcodec/avcodec.h presence... no
| checking for libav/libavcodec/avcodec.h... no
| checking avcodec.h usability... no
| checking avcodec.h presence... no
| checking for avcodec.h... no
| checking ffmpeg/avcodec.h usability... no
| checking ffmpeg/avcodec.h presence... no
| checking for ffmpeg/avcodec.h... no
| checking libav/avcodec.h usability... no
| checking libav/avcodec.h presence... no
| checking for libav/avcodec.h... no
| checking libavformat/avformat.h usability... yes
| checking libavformat/avformat.h presence... yes
| checking for libavformat/avformat.h... yes
| checking ffmpeg/libavformat/avformat.h usability... no
| checking ffmpeg/libavformat/avformat.h presence... no
| checking for ffmpeg/libavformat/avformat.h... no
| checking libav/libavformat/avformat.h usability... no
| checking libav/libavformat/avformat.h presence... no
| checking for libav/libavformat/avformat.h... no
| checking avformat.h usability... no
| checking avformat.h presence... no
| checking for avformat.h... no
| checking ffmpeg/avformat.h usability... no
| checking ffmpeg/avformat.h presence... no
| checking for ffmpeg/avformat.h... no
| checking libav/avformat.h usability... no
| checking libav/avformat.h presence... no
| checking for libav/avformat.h... no
| checking jpeglib.h usability... yes
| checking jpeglib.h presence... yes
| checking for jpeglib.h... yes
| checking sqlite3.h usability... yes
| checking sqlite3.h presence... yes
| checking for sqlite3.h... yes
| checking libexif/exif-loader.h usability... yes
| checking libexif/exif-loader.h presence... yes
| checking for libexif/exif-loader.h... yes
| checking id3tag.h usability... yes
| checking id3tag.h presence... yes
| checking for id3tag.h... yes
| checking ogg/ogg.h usability... yes
| checking ogg/ogg.h presence... yes
| checking for ogg/ogg.h... yes
| checking vorbis/codec.h usability... yes
| checking vorbis/codec.h presence... yes
| checking for vorbis/codec.h... yes
| checking FLAC/metadata.h usability... no
| checking FLAC/metadata.h presence... no
| checking for FLAC/metadata.h... no
| checking for jpeglib.h... (cached) yes
| checking for sqlite3.h... (cached) yes
| checking for libexif/exif-loader.h... (cached) yes
| checking for id3tag.h... (cached) yes
| checking for ogg/ogg.h... (cached) yes
| checking for vorbis/codec.h... (cached) yes
| checking FLAC/metadata.h usability... no
| checking FLAC/metadata.h presence... no
| checking for FLAC/metadata.h... no
| configure: error: libFLAC headers not found or not usable
| NOTE: The following config.log files may provide further information.
| NOTE: /home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/work/sh4-oe-linux/readymedia/1.1.0+gitAUTOINC+bb9d584a86-r0/git/config.log
| ERROR: configure failed
| WARNING: /home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/work/sh4-oe-linux/readymedia/1.1.0+gitAUTOINC+bb9d584a86-r0/temp/run.do_configure.9544:1 exit 1 from 'exit 1'
| ERROR: Function failed: do_configure (log file is located at /home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/build/tmp/work/sh4-oe-linux/readymedia/1.1.0+gitAUTOINC+bb9d584a86-r0/temp/log.do_configure.9544)
ERROR: Task 2888 (/home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/meta-openpli/recipes-multimedia/readymedia/readymedia.bb, do_configure) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3178 tasks of which 2383 didn't need to be rerun and 1 failed.
Waiting for 0 running tasks to finish:

Summary: 1 task failed:
  /home/sodo/Bureau/pli/vuplus-fulan-openpli-oe-core/meta-openpli/recipes-multimedia/readymedia/readymedia.bb, do_configure
Summary: There were 6 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

**Comment by Taapat** [comment]
Sorry, but in this moment I am stopped spark support.
Spark uses old glibc and old kernel, so definitely need a patch for it.

You can look, maybe you find something useful in oe-alliance.
Or simply remove enigma2-plugin-extensions-dlnaserver from feed packages.
I've never built feed in spark, only image, so I assume that there also may be problems with other packages.

**Comment by kingvuplus** [comment]
yes taapat i have deleted readymedia and replace mimidlna and build with not any other probleme

thank you
