### ISSUE TITLE
For Xbmc

### ISSUE THREAD

**Issue by kingvuplus** [Taapat/vuplus-openpli-oe-core#15]
Hello taapat 

It Possible To Build Xbmc To run Directly To Vu+ solo2 like E2Bmc

what is The File needed To build Xbmc and Run it directly 

thank you

**Comment by Taapat** [comment]
If you are able to devote enough time for it, it is definitely possible.
If you think that I can recommend you ready and working solution, then I do not know such.

Why do you want to run xbmc directly? Why you don't want to use the plugin?
I personally have no interest in it, but you can look for example mx3L kodiext: https://github.com/mx3L/kodiext

http://forums.openpli.org/topic/40225-kodi-152-for-vusolose-vusolo2-and-vuduo2/

**Comment by kingvuplus** [comment]
thank's taapat 

i want to test and compare xbmc media center and E2 

i dont't like the Plugin launcher i think if xbmc run directly work Perfect in solo2

i dont have any idea how to add code into source for run it directly

if you have any idea Please send me for testing

thank you
