### ISSUE TITLE
Build Error for Spark 7111 on Linux Mint 13

### ISSUE THREAD

**Issue by linuxstv** [Taapat/vuplus-openpli-oe-core#16]
Hi bro,
Need help to solve this error:

> DEBUG: Executing python function sysroot_cleansstate
> DEBUG: Python function sysroot_cleansstate finished
> DEBUG: Executing shell function autotools_preconfigure
> DEBUG: Shell function autotools_preconfigure finished
> DEBUG: Executing python function autotools_copy_aclocals
> DEBUG: Python function autotools_copy_aclocals finished
> DEBUG: Executing shell function do_configure
> 
> ERROR: "gcc " cannot build an executable (is your linker broken?)
> 
> WARNING: /home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/work/i686-linux/qemu-native/2.6.0-r1/temp/run.do_configure.19223:1 exit 1 from '/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/work/i686-linux/qemu-native/2.6.0-r1/qemu-2.6.0/configure --prefix=/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/i686-linux/usr --sysconfdir=/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/i686-linux/etc --libexecdir=/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/i686-linux/usr/libexec --localstatedir=/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/i686-linux/var --disable-strip --target-list=arm-linux-user,arm-softmmu,aarch64-linux-user,aarch64-softmmu,i386-linux-user,i386-softmmu,mips-linux-user,mips-softmmu,mipsel-linux-user,mipsel-softmmu,mips64-linux-user,mips64-softmmu,mips64el-linux-user,mips64el-softmmu,ppc-linux-user,ppc-softmmu,sh4-linux-user,sh4-softmmu,x86_64-linux-user,x86_64-softmmu --disable-werror --disable-bluez --disable-libiscsi --with-system-pixman --extra-cflags='-isystem/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/i686-linux/usr/include -march=native -O2 -pipe' --audio-drv-list=oss,alsa --disable-linux-aio --disable-bzip2 --disable-curses --enable-fdt --disable-gcrypt --disable-opengl --disable-gnutls --disable-gtk --disable-vte --disable-cap-ng --disable-curl --disable-libusb --disable-lzo --disable-nettle --disable-smartcard --disable-numa --disable-sdl --disable-libssh2 --enable-uuid --disable-virtfs --disable-vnc-jpeg --disable-vnc-png --disable-vnc-sasl --disable-xen --disable-xfsctl $KVMOPTS'
> ERROR: Function failed: do_configure (log file is located at /home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/work/i686-linux/qemu-native/2.6.0-r1/temp/log.do_configure.19223)

That is the log before the build process exit.

**Comment by linuxstv** [comment]
So sorry, my bad for using old version of the GCC. After updating to version 4.9.4, the error has gone.

**Comment by Taapat** [comment]
Thank you for the information, I am glad that you yourself solve this problem.
I suppose it could be useful also for others.
