### ISSUE TITLE
Error After Update To Latest Commit

### ISSUE THREAD

**Issue by linuxstv** [Taapat/vuplus-openpli-oe-core#17]
Hi bro,
I've updated today, and after bitbake openpli-enigma2-image, I got this error:

> ERROR: gstreamer1.0-plugin-dvbmediasink-1.9.9+gitAUTOINC+2458954fe6-r0 do_compile: oe_runmake failed
> ERROR: gstreamer1.0-plugin-dvbmediasink-1.9.9+gitAUTOINC+2458954fe6-r0 do_compile: Function failed: do_compile (log file is located at /home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/work/spark-oe-linux/gstreamer1.0-plugin-dvbmediasink/1.9.9+gitAUTOINC+2458954fe6-r0/temp/log.do_compile.6483)
> ERROR: Logfile of failure stored in: /home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/work/spark-oe-linux/gstreamer1.0-plugin-dvbmediasink/1.9.9+gitAUTOINC+2458954fe6-r0/temp/log.do_compile.6483
> Log data follows:
> | DEBUG: SITE files ['endian-little', 'bit-32', 'sh-common', 'common-linux', 'common-glibc', 'sh4-linux', 'common']
> | DEBUG: Executing shell function do_compile
> | NOTE: make -j 2
> | ERROR: oe_runmake failed
> | make  all-am
> | make[1]: Entering directory `/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/work/spark-oe-linux/gstreamer1.0-plugin-dvbmediasink/1.9.9+gitAUTOINC+2458954fe6-r0/build'
> | ./sh4-oe-linux-libtool  --tag=CC   --mode=compile sh4-oe-linux-gcc  -ml -m4 --sysroot=/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark -DHAVE_CONFIG_H -I. -I../git    -pthread -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/include/gstreamer-1.0 -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/lib/gstreamer-1.0/include -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/include/glib-2.0 -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/lib/glib-2.0/include   -pthread -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/include/gstreamer-1.0 -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/lib/gstreamer-1.0/include -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/include/glib-2.0 -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/lib/glib-2.0/include  -Os -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/work/spark-oe-linux/gstreamer1.0-plugin-dvbmediasink/1.9.9+gitAUTOINC+2458954fe6-r0=/usr/src/debug/gstreamer1.0-plugin-dvbmediasink/1.9.9+gitAUTOINC+2458954fe6-r0 -fdebug-prefix-map=/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/i686-linux= -fdebug-prefix-map=/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark= -c -o libgstdvbvideosink_la-gstdvbvideosink.lo`test -f 'gstdvbvideosink.c' || echo '../git/'`gstdvbvideosink.c
> | ./sh4-oe-linux-libtool  --tag=CC   --mode=compile sh4-oe-linux-gcc  -ml -m4 --sysroot=/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark -DHAVE_CONFIG_H -I. -I../git    -pthread -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/include/gstreamer-1.0 -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/lib/gstreamer-1.0/include -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/include/glib-2.0 -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/lib/glib-2.0/include   -pthread -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/include/gstreamer-1.0 -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/lib/gstreamer-1.0/include -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/include/glib-2.0 -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/lib/glib-2.0/include  -Os -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/work/spark-oe-linux/gstreamer1.0-plugin-dvbmediasink/1.9.9+gitAUTOINC+2458954fe6-r0=/usr/src/debug/gstreamer1.0-plugin-dvbmediasink/1.9.9+gitAUTOINC+2458954fe6-r0 -fdebug-prefix-map=/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/i686-linux= -fdebug-prefix-map=/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark= -c -o libgstdvbaudiosink_la-gstdvbaudiosink.lo`test -f 'gstdvbaudiosink.c' || echo '../git/'`gstdvbaudiosink.c
> | sh4-oe-linux-libtool: compile:  sh4-oe-linux-gcc -ml -m4 --sysroot=/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark -DHAVE_CONFIG_H -I. -I../git -pthread -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/include/gstreamer-1.0 -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/lib/gstreamer-1.0/include -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/include/glib-2.0 -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/lib/glib-2.0/include -pthread -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/include/gstreamer-1.0 -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/lib/gstreamer-1.0/include -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/include/glib-2.0 -I/home/budiarno/Source/Enigmsh4-oe-linux-libtool: compile:  sh4-oe-linux-gcc -ml -m4 --sysroot=/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark -DHAVE_CONFIG_H -I. -I../git -pthread -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/include/gstreamer-1.0 -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/lib/gstreamer-1.0/include -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/include/glib-2.0 -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/lib/glib-2.0/include -pthread -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/include/gstreamer-1.0 -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/lib/gstreamer-1.0/include -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/include/glib-2.0 -I/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/lib/glib-2.0/include -Os -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/work/spark-oe-linux/gstreamer1.0-plugin-dvbmediasink/1.9.9+gitAUTOINC+2458954fe6-r0=/usr/src/debug/gstreamer1.0-plugin-dvbmediasink/1.9.9+gitAUTOINC+2458954fe6-r0 -fdebug-prefix-map=/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/i686-linux= -fdebug-prefix-map=/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark= -c ../git/gstdvbvideosink.c  -fPIC -DPIC -o .libs/libgstdvbvideosink_la-gstdvbvideosink.o
> | a2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark/usr/lib/glib-2.0/include -Os -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/work/spark-oe-linux/gstreamer1.0-plugin-dvbmediasink/1.9.9+gitAUTOINC+2458954fe6-r0=/usr/src/debug/gstreamer1.0-plugin-dvbmediasink/1.9.9+gitAUTOINC+2458954fe6-r0 -fdebug-prefix-map=/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/i686-linux= -fdebug-prefix-map=/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/sysroots/spark= -c ../git/gstdvbaudiosink.c  -fPIC -DPIC -o .libs/libgstdvbaudiosink_la-gstdvbaudiosink.o
> | ../git/gstdvbaudiosink.c:68:34: fatal error: linux/dvb/stm_ioctls.h: No such file or directory
> |  #include <linux/dvb/stm_ioctls.h>
> |                                   ^
> | ../git/gstdvbvideosink.c:68:34: fatal error: linux/dvb/stm_ioctls.h: No such file or directory
> |  #include <linux/dvb/stm_ioctls.h>
> |                                   ^
> | compilation terminated.
> | compilation terminated.
> | make[1]: *** [libgstdvbvideosink_la-gstdvbvideosink.lo] Error 1
> | make[1]: *** Waiting for unfinished jobs....
> | make[1]: *** [libgstdvbaudiosink_la-gstdvbaudiosink.lo] Error 1
> | make[1]: Leaving directory`/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/work/spark-oe-linux/gstreamer1.0-plugin-dvbmediasink/1.9.9+gitAUTOINC+2458954fe6-r0/build'
> | make: **\* [all] Error 2
> | WARNING: /home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/work/spark-oe-linux/gstreamer1.0-plugin-dvbmediasink/1.9.9+gitAUTOINC+2458954fe6-r0/temp/run.do_compile.6483:1 exit 1 from 'exit 1'
> | ERROR: Function failed: do_compile (log file is located at /home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/build/tmp/work/spark-oe-linux/gstreamer1.0-plugin-dvbmediasink/1.9.9+gitAUTOINC+2458954fe6-r0/temp/log.do_compile.6483)
> ERROR: Task (/home/budiarno/Source/Enigma2/vuplus-fulan-openpli-oe-core/meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0-plugin-dvbmediasink.bb:do_compile) failed with exit code '1'

Where should I find this file:

> ../git/gstdvbvideosink.c:68:34: fatal error: linux/dvb/stm_ioctls.h: No such file or directory
> |  #include <linux/dvb/stm_ioctls.h>

stm_ioctls.h error?

**Comment by Taapat** [comment]
If you see that I update openembedded, then please wait some time before use the latest version.
I need some time to build the images and correct all errors.
Your pull requests with the corrections are welcome to make the time shorter.

**Comment by linuxstv** [comment]
Ok thank you bro, for the moment I got to change its "include" line to a file "stm_ioctls.h" that I copied from Player2 source. I'll wait for the fix.

**Comment by Taapat** [comment]
I just finished building image for my fulan 7111.

Try to update and build now.

I wanted to add that I do not have any error with gstreamer1.0-plugin-dvbmediasink and I'm not  corrected anything specially for it.
