### ISSUE TITLE
New STB build !

### ISSUE THREAD

**Issue by mihaip1948** [Taapat/vuplus-openpli-oe-core#2]
Hi Taapat ! are you interested in building a OpenPLi 5.0 image
for a pretty interesting STB ? almost  the same configuration
as VU+Zero ...

**Comment by Taapat** [comment]
Sorry, but I don't want to build the image for receivers that I can't test.
I have VU+ Solo2 and Amiko SHD-8900 Alien, so I build the image only for those receivers.
And I not have so much free time for it.

But you can use my git to build the images for the other receivers.
If something is necessary to change, create pull request and I accept it.

**Comment by mihaip1948** [comment]
Nooo ! the ideea is ... I can provide you a receiver based on
bcm7362 pretty similar to VU+Zero or ET7000 ... if you are
interested ! I'm not an expert in building images ... but you
are ... I'm following you since AR-P ...

**Comment by Taapat** [comment]
In this moment I'm not too interested in it.
Taking receiver from you, I need to provide some support for it.
But I do not want to spend my time to to solve user problems if they not actual or interesting for my.

**Comment by mihaip1948** [comment]
OK ... I understand it ! anyway the ideea is to build
just a basic OpenPLi 5.0 ... good to evaluate or to
be used as alternative to the factory image ... OpenATV
even a backup type was OK !

**Comment by mihaip1948** [comment]
I've tested your build for Alien1 !!! good work ! but ...
- the Oscam must be replaced with a more recent one ... I did it
  and is working perfectly ( http://download.oscam.cc )
- there is a problem with mapping of the KodiDirect 3.0 menu on
  the screen ! is smaller then must be and placed into the uper left 
  corner ... you can see here ... http://www.sat-support.tv/forum/viewtopic.php?p=27734#p27734

Thew system is working smooth ! congratulations !

**Comment by Taapat** [comment]
1. I do not provide by default emu support. The ones you can find on the feed comes from users and I did not pay attention to their renewal.
   For myself, I regularly compiled the latest version of  oscam from streambord, but I do not put it on the feed, because I compiled only with options that I use myself.
2. It's only the plugin skin problem. If you are using full HD skin, then you need also a full HD skins for the plugins that you use.

**Comment by mihaip1948** [comment]
For me the ideea of 720p skin was OK ! is only a skin ! I did not feel
till now the need of a FullHD skin ... and the problem remains ... all
the present plugins have 720p menu !!! converting all of them into 1080
will take years ... if will be done !

**Comment by mihaip1948** [comment]
Memory usage statistics shows the total memory ... MemTotal=116520 kB !!! and
MemFree=2756kB ... is'nt too small ? from phisical 256 Mb of RAM ... probably
64 Mb is used as video buffer but the rest ?

P.S. Sorry ! I just saw the bootloader detects ... 128 MB of RAM !!!
but looking on tech specs for Alien1  ... 128kB*2 ... what the hell it means ?

**Comment by mihaip1948** [comment]
The skin problem was a false one ! the plugin KodiDirect allready have a config option
to use a hiresolution skin !!! you've right ... was a plugin problem !
