### ISSUE TITLE
Missing uniontunertype for building spark7162

### ISSUE THREAD

**Issue by joeusercz** [Taapat/vuplus-openpli-oe-core#3]
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'enigma2-plugin-systemplugins-uniontunertype'. Close matches:
  enigma2-plugin-systemplugins-dlnabrowser
  enigma2-plugin-systemplugins-autoshutdown
  enigma2-plugin-systemplugins-satscan
  enigma2-plugins RPROVIDES enigma2-plugin-systemplugins-uniontunertype
ERROR: Required build target 'openpli-enigma2-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['openpli-enigma2-image', 'enigma2-plugin-systemplugins-uniontunertype']

**Comment by Taapat** [comment]
I remove plugin uniontunertype from spark7162.conf: https://github.com/Taapat/vuplus-fulan-openpli-oe-core/commit/bd04edc08620e00acac17028906e40f51cbb9340
If it's required for someone then please offer a bb file for it.

**Comment by joeusercz** [comment]
Yes, I removed it from spark7162.conf to enable building. It is not absolutely required, but it is very helpful in order to switch the tuner config between dvb-c and dvb-t. If I knew how to make a bb file for it I would... :)
