### ISSUE TITLE
Error when build

### ISSUE THREAD

**Issue by kingvuplus** [Taapat/vuplus-openpli-oe-core#7]
error when build for spark 7162 in dvb-module  any idea to fix that taapat

Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 2 -e MAKEFLAGS= KERNEL_SRC=/home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-source KERNEL_PATH=/home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-source KERNEL_SRC=/home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-source KERNEL_VERSION=2.6.32.61_stm24_0217 -C /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-source O=/home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-build-artifacts SPARK7162=1 M=/home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work/spark7162-oe-linux/fulan-dvb-modules/2.6.32.61-stm24-0217+20151114-r36/git V=1 ARCH=sh PLAYER191=player191 DRIVER_TOPDIR=/home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work/spark7162-oe-linux/fulan-dvb-modules/2.6.32.61-stm24-0217+20151114-r36/git KERNEL_LOCATION=/home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/s
| make: Entering directory `/home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-source'
| make -C /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-build-artifacts \
|   KBUILD_SRC=/home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-source \
|   KBUILD_EXTMOD="/home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work/spark7162-oe-linux/fulan-dvb-modules/2.6.32.61-stm24-0217+20151114-r36/git" -f /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-source/Makefile \
|   modules
| make[1]: Entering directory`/home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-build-artifacts'
|   CC [M]  /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work/spark7162-oe-linux/fulan-dvb-modules/2.6.32.61-stm24-0217+20151114-r36/git/frontends/spark7162/tuner/MxL301_Ext/mxL_user_define.o
| In file included from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/sysroots/spark7162/usr/include/features.h:365:0,
|                  from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/sysroots/spark7162/usr/include/unistd.h:25,
|                  from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work/spark7162-oe-linux/fulan-dvb-modules/2.6.32.61-stm24-0217+20151114-r36/git/frontends/spark7162/tuner/MxL301_Ext/mxL_user_define.c:33:
| /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/sysroots/spark7162/usr/include/sys/cdefs.h:236:0: warning: "**attribute_const**" redefined [enabled by default]
|  # define **attribute_const** **attribute** ((**const**))
|  ^
| In file included from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-source/include/linux/compiler.h:40:0,
|                  from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-source/include/linux/linkage.h:4,
|                  from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-source/include/linux/kernel.h:11,
|                  from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-source/include/linux/delay.h:10,
|                  from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work/spark7162-oe-linux/fulan-dvb-modules/2.6.32.61-stm24-0217+20151114-r36/git//frontends/spark_common/ywdefs.h:30,
|                  from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work/spark7162-oe-linux/fulan-dvb-modules/2.6.32.61-stm24-0217+20151114-r36/git//frontends/spark7162/6158/types.h:37,
|                  from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work/spark7162-oe-linux/fulan-dvb-modules/2.6.32.61-stm24-0217+20151114-r36/git/frontends/spark7162/tuner/MxL301_Ext/mxL_user_define.c:26:
| /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-source/include/linux/compiler-gcc.h:80:0: note: this is the location of the previous definition
|  #define **attribute_const**  **attribute**((**const**))
|  ^
| In file included from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/sysroots/spark7162/usr/include/features.h:365:0,
|                  from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/sysroots/spark7162/usr/include/unistd.h:25,
|                  from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work/spark7162-oe-linux/fulan-dvb-modules/2.6.32.61-stm24-0217+20151114-r36/git/frontends/spark7162/tuner/MxL301_Ext/mxL_user_define.c:33:
| /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/sysroots/spark7162/usr/include/sys/cdefs.h:307:0: warning: "**always_inline" redefined [enabled by default]
|  # define __always_inline __inline __attribute** ((**always_inline**))
|  ^
| In file included from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-source/include/linux/compiler-gcc.h:86:0,
|                  from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-source/include/linux/compiler.h:40,
|                  from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-source/include/linux/linkage.h:4,
|                  from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-source/include/linux/kernel.h:11,
|                  from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-source/include/linux/delay.h:10,
|                  from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work/spark7162-oe-linux/fulan-dvb-modules/2.6.32.61-stm24-0217+20151114-r36/git//frontends/spark_common/ywdefs.h:30,
|                  from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work/spark7162-oe-linux/fulan-dvb-modules/2.6.32.61-stm24-0217+20151114-r36/git//frontends/spark7162/6158/types.h:37,
|                  from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work/spark7162-oe-linux/fulan-dvb-modules/2.6.32.61-stm24-0217+20151114-r36/git/frontends/spark7162/tuner/MxL301_Ext/mxL_user_define.c:26:
| /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-source/include/linux/compiler-gcc4.h:15:0: note: this is the location of the previous definition
|  #define **always_inline  inline __attribute**((always_inline))
|  ^
| In file included from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-source/include/linux/delay.h:14:0,
|                  from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work/spark7162-oe-linux/fulan-dvb-modules/2.6.32.61-stm24-0217+20151114-r36/git//frontends/spark_common/ywdefs.h:30,
|                  from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work/spark7162-oe-linux/fulan-dvb-modules/2.6.32.61-stm24-0217+20151114-r36/git//frontends/spark7162/6158/types.h:37,
|                  from /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work/spark7162-oe-linux/fulan-dvb-modules/2.6.32.61-stm24-0217+20151114-r36/git/frontends/spark7162/tuner/MxL301_Ext/mxL_user_define.c:26:
| /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-source/arch/sh/include/asm/delay.h:18:44: error: expected ')' before '?' token
|  #define udelay(n) (__builtin_constant_p(n) ? \
|                                             ^
| /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work/spark7162-oe-linux/fulan-dvb-modules/2.6.32.61-stm24-0217+20151114-r36/git//frontends/spark_common/ywdefs.h:112:23: note: in expansion of macro 'udelay'
|  #define usleep(us)    udelay(us)
|                        ^
| /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/sysroots/spark7162/usr/include/unistd.h:463:12: note: in expansion of macro 'usleep'
|  extern int usleep (__useconds_t __useconds);
|             ^
| make[3]: **\* [/home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work/spark7162-oe-linux/fulan-dvb-modules/2.6.32.61-stm24-0217+20151114-r36/git/frontends/spark7162/tuner/MxL301_Ext/mxL_user_define.o] Error 1
| make[2]: **\* [/home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work/spark7162-oe-linux/fulan-dvb-modules/2.6.32.61-stm24-0217+20151114-r36/git/frontends] Error 2
| make[1]: **\* [_module_/home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work/spark7162-oe-linux/fulan-dvb-modules/2.6.32.61-stm24-0217+20151114-r36/git] Error 2
| make[1]: Leaving directory `/home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-build-artifacts'
| make: *** [sub-make] Error 2
| make: Leaving directory`/home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work-shared/spark7162/kernel-source'
| ERROR: oe_runmake failed
| ERROR: Function failed: do_compile (log file is located at /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/build/tmp/work/spark7162-oe-linux/fulan-dvb-modules/2.6.32.61-stm24-0217+20151114-r36/temp/log.do_compile.25453)
ERROR: Task 2230 (/home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/meta-fulan/recipes-drivers/fulan-dvb-modules.bb, do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2897 tasks of which 2895 didn't need to be rerun and 1 failed.
Waiting for 0 running tasks to finish:
Summary: 1 task failed:
  /home/sodo/Bureau/OECORE/vuplus-openpli-oe-core/meta-fulan/recipes-drivers/fulan-dvb-modules.bb, do_compile

**Comment by Taapat** [comment]
It looks like you have exactly the same problem as here: https://github.com/Taapat/vuplus-fulan-openpli-oe-core/issues/4
On which systems you are building?
It seems that for 7162 something is wrong with the drivers.
But I have 7111 receiver, so I can not promise that in the near future I can check this and fix.

But if you find a solution, then I will be happy to accept a pull request.

**Comment by kingvuplus** [comment]
i am in Ubuntu 14.04 32 bit  but when i build from OE-alliance for 7162 i d'ont have any probleme

**Comment by Taapat** [comment]
I have taken many things from the AR-P instead of OE-alliance.
But I have not checked anything for 7162

**Comment by kingvuplus** [comment]
ok taapat thank you

**Comment by Taapat** [comment]
Try after this fix: https://github.com/Taapat/driver/commit/fb155c18d2f9a6059e8cce30114e75217b06cd5a

**Comment by joeusercz** [comment]
(Almost) works with new fix - thanks.

Problem with mountspark in do_rootfs missing depmod.

I do not care about mountspark, so I removed it and it builds ok without it.

**Comment by Taapat** [comment]
I hope this fix mountspark: https://github.com/Taapat/vuplus-fulan-openpli-oe-core/commit/8776d64d24b3e7f2aaf9e0316c41eeeb5c32b25a

**Comment by joeusercz** [comment]
I wanted to try your fix, but I cannot update...

> ~/vuplus-fulan-openpli-oe-core$ make update
> Updating Git repositories...
> Already up-to-date.
> Synchronizing submodule url for 'meta-openpli/recipes-openpli/e2openplugins'
> Synchronizing submodule url for 'oe-bitbake'
> Synchronizing submodule url for 'oe-meta-openembedded'
> Synchronizing submodule url for 'oe-openembedded-core'
> Cloning into 'oe-bitbake'...
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> Clone of 'git@github.com:openembedded/bitbake.git' into submodule path 'oe-bitbake' failed
> Makefile:82: recipe for target 'update' failed
> make: **\* [update] Error 1

**Comment by Taapat** [comment]
Maybe they are some problems on github?
Maybe try again?
"git clone git@github.com:openembedded/bitbake.git" work without any problems on your system?
If nothing not help, then I think you should try everything from the beginning.

**Comment by kingvuplus** [comment]
ok thank you

**Comment by Taapat** [comment]
Sorry, I fix this error: https://github.com/Taapat/vuplus-fulan-openpli-oe-core/commit/c3aa040eb07d03c5beba2527872a18a4fe6ce9a5

**Comment by joeusercz** [comment]
Thanks, working now.
